### ISSUE TITLE
关于null的问题

### ISSUE THREAD

**Issue by linxingfang** [node-webot/wechat#152]
..\node_modules\wechat\lib\util.js:11
    if (data.errcode) {
            ^
TypeError: Cannot read property 'errcode' of null

如果errcode为null，不应该报错的啊？

**Comment by JacksonTian** [comment]
堆栈能给长一点吗

**Comment by JacksonTian** [comment]
看起来你用的版本很老了。升级下吧。这个问题貌似fix过

**Comment by wanglihui** [comment]
使用supertest或者curl发送请求到 wechat("sometoken", function(req, res, next){}) 创建的路由时，总是提示超时，具体代码如下:
```
it("should be ok POST /weixin/cb with correct token", function(done) {
    var tail = support.tail("123456");
    var info = {
      sp: "fuck",
      user: 'caohua',
      type: 'event',
      event: 'subscribe'
    }
    request(app)
      .post('/weixin/cb'+tail)
      .send(support.template(info))
      .end(function(err, res) {
        if (err) {
          throw err;
        } else {
          console.info(res.status);
          console.info(res);
          done();
        }
      });
  })
```

返回结果:
```
  1 failing

  1) routes/index.js should be ok POST /weixin/cb with correct token:
     <b>Error: timeout of 2000ms exceeded</b>
      at null.<anonymous> (C:\Users\YCXJ\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:139:19)
      at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

测试了几个版本（0.8.11， 0.8.19），均有此问题。代码使用express4.0 + window8

**Comment by wanglihui** [comment]
服务器端代码：
```
var express = require('express');
var router = express.Router();
var wechat = require('wechat');

/* GET home page. */
router.get('/', function(req, res) {
  res.render('index', { title: 'Express' });
});

router.use('/weixin', wechat('123456', function(req, res, next) {
  next();
}));

router.all('/weixin/cb', function(req, res, next) {
  res.reply("test");
});


module.exports = router;
```

貌似是在 wechat/lib/wechat.js 的 load方法中   stream.on('data') stream.on('end') 无法触发，导致callback  一直没有执行

**Comment by wanglihui** [comment]
可以加一句判断 if (data && data.errcode)

**Comment by JacksonTian** [comment]
升级版本后 还有这个问题吗

**Comment by linxingfang** [comment]
没升级，这个程序执行了30000次也就出错4、5次错，有点奇怪

**Comment by JacksonTian** [comment]
升级后 如果还有此问题 请reopen这一条。
