### ISSUE TITLE
connect 用的哪个版本

### ISSUE THREAD

**Issue by yishenggudou** [node-webot/wechat#169]
```
/data/apps/weixinbot/bot.js:12
app.use(connect.query()); // Or app.use(express.query());
                ^
TypeError: Object function createServer() {
  function app(req, res, next){ app.handle(req, res, next); }
  merge(app, proto);
  merge(app, EventEmitter.prototype);
  app.route = '/';
  app.stack = [];
  return app;
} has no method 'query'
    at Object.<anonymous> (/data/apps/weixinbot/bot.js:12:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by JacksonTian** [comment]
自己加querystring解析的中间件即可。

**Comment by yishenggudou** [comment]
安装2.5 版本搞定
