### ISSUE TITLE
error caching token

### ISSUE THREAD

**Issue by dcsan** [node-webot/wechat#192]
I'm using this code below to create the token but getting an error

```
mbot:WeChatAdapter api.sendText > { [Error: ENOENT, open '/root/www/WeBot/data/access_token.txt']
  errno: -2,
  code: 'ENOENT',
  path: '/root/www/WeBot/data/access_token.txt' } undefined
```

I don't quite follow your code, but i am guessing: if the file doesn't exist or there is an error
then it should call the second callback to create the file?
but that doesn't seem to be happening...

```
// typescript

import AppConfig = require("../../config/AppConfig");

var fs = require("fs");
var API = require("wechat-api");

var debug = require("debug")("mbot:wcApi");
var path = require("path");
var base = path.resolve(".");
var tokenPath = path.join(base, "data/access_token.txt");
console.log("tokenPath", tokenPath);


var wcApi = new API(AppConfig.WECHAT_APPID, AppConfig.WECHAT_SECRET, function(callback) {
    // 传入一个获取全局token的方法
    fs.readFile(tokenPath, "utf8", function(err, txt) {
        if (err) {
            debug("error reading file");
            return callback(err);
        }
        debug("reading wcAPI key");
        callback(null, JSON.parse(txt));
    });
}, function(token, callback) {
    // 请将token存储到全局，跨进程、跨机器级别的全局，比如写到数据库、redis等
    // 这样才能在cluster模式及多机情况下使用，以下为写入到文件的示例
    debug("writing wcAPI key", tokenPath);
    fs.writeFile(tokenPath, JSON.stringify(token), callback);
});

debug("created wcApi", wcApi);

export = wcApi;
```

**Comment by JacksonTian** [comment]
touch the file first.

**Comment by dcsan** [comment]
yep, i did touch the file, but then get a different error on reading it:

```
WeBot-0 Sun, 11 Oct 2015 06:47:57 GMT mbot:wcApi reading wcAPI key
WeBot-0 SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /root/www/WeBot/src/adapters/WeChat/CoreApi.js:17:29
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
```

since it is trying to parse an empty file?

if the file is touched/exists it won't create it either.

i did also check permissions that the account running the node process is able to write the file.
