### ISSUE TITLE
App is not defined

### ISSUE THREAD

**Issue by yuxuanchen1997** [node-webot/wechat#196]
示例代码nodejs执行失败, 错误信息
app.use(express.query());
^
ReferenceError: app is not defined
    at Object.<anonymous> (/home/yuxuan/vote/wechatnew.js:8:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by JacksonTian** [comment]
Learn how to use connect or express first.
