### ISSUE TITLE
解析xml报错

### ISSUE THREAD

**Issue by chenws1999** [node-webot/wechat#278]
应用场景: 微信三方平台开发
描述: 在开发微信三方平台过程中,在解密微信发过来的component_ticket事件的postdata的时候报错.
初步分析是解密之后得到乱码字符串,进而导致xml2js解析过程中报错. 求解

错误详情:

```
BadMessageError: Non-whitespace before first tag.
Line: 0
Column: 1
Char: �
    at error (/home/user1/code/myProject/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/home/user1/code/myProject/node_modules/sax/lib/sax.js:677:7)
    at beginWhiteSpace (/home/user1/code/myProject/node_modules/sax/lib/sax.js:951:7)
    at SAXParser.write (/home/user1/code/myProject/node_modules/sax/lib/sax.js:1006:11)
    at Parser.exports.Parser.Parser.parseString (/home/user1/code/myProject/node_modules/wechat/node_modules/xml2js/lib/xml2js.js:508:31)
    at Parser.parseString (/home/user1/code/myProject/node_modules/wechat/node_modules/xml2js/lib/xml2js.js:7:59)
    at Object.exports.parseString (/home/user1/code/myProject/node_modules/wechat/node_modules/xml2js/lib/xml2js.js:540:19)
    at /home/user1/code/myProject/node_modules/wechat/lib/wechat.js:481:16
    at Parser.<anonymous> (/home/user1/code/myProject/node_modules/wechat/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at SAXParser.onclosetag (/home/user1/code/myProject/node_modules/wechat/node_modules/xml2js/lib/xml2js.js:447:26)
    at emit (/home/user1/code/myProject/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/user1/code/myProject/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/home/user1/code/myProject/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/home/user1/code/myProject/node_modules/sax/lib/sax.js:1436:13)
```

**Comment by JacksonTian** [comment]
？？？？？

**Comment by chenws1999** [comment]
抱歉 是我密钥配错了 很抱歉,打扰了
